version: "3.9"
services:
  database:
    hostname: db_host
    image: "postgres:13.2-alpine"
    env_file:
      - database.env
    ports:
      - "5432:5432"
  request-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - database
    depends_on:
      - database
    environment:
      - DATABASE_URL=jdbc:postgresql://db_host:5432/
    env_file:
      - database.env